// apps/web/src/aphrody/features/assistant/Assistant.tsx
// Assistant chat surface (React port of Angular AssistantComponent): Gemini-style hero + composer + conversation, sending runs `aphrody chat --prompt`.

import { useCallback, useEffect, useRef, useState } from "react";
import { MdAssistChip, MdChipSet, MdIcon, MdIconButton, MdMenuItem } from "@aphrody-code/m3-react";
import { run } from "../../client.ts";
import { Menu } from "../../../components/ui/Menu.tsx";
import { VoiceOverlay } from "./VoiceOverlay.tsx";

function voiceSupported(): boolean {
  if (typeof window === "undefined") return false;
  const w = window as unknown as { SpeechRecognition?: unknown; webkitSpeechRecognition?: unknown };
  return Boolean(w.SpeechRecognition ?? w.webkitSpeechRecognition);
}

// ── Attachment model (ported from the Angular `attachment.ts` helper) ────────

type AttachmentKind = "image" | "video" | "audio" | "github" | "url" | "drive" | "file";

interface Attachment {
  id: string;
  kind: AttachmentKind;
  name: string;
  detail?: string;
  text?: string;
  loading?: boolean;
  note?: string;
}

function kindIcon(kind: AttachmentKind): string {
  switch (kind) {
    case "image":
      return "image";
    case "video":
      return "movie";
    case "audio":
      return "graphic_eq";
    case "github":
      return "code";
    case "url":
      return "link";
    case "drive":
      return "cloud";
    default:
      return "description";
  }
}

function kindLabel(kind: AttachmentKind): string {
  switch (kind) {
    case "image":
      return "Image";
    case "video":
      return "Vidéo";
    case "audio":
      return "Audio";
    case "github":
      return "GitHub";
    case "url":
      return "Lien";
    case "drive":
      return "Drive";
    default:
      return "Fichier";
  }
}

const TEXT_EXT = new Set([
  "txt",
  "md",
  "markdown",
  "rs",
  "ts",
  "tsx",
  "js",
  "jsx",
  "mjs",
  "cjs",
  "json",
  "jsonc",
  "toml",
  "yaml",
  "yml",
  "html",
  "htm",
  "css",
  "scss",
  "sass",
  "less",
  "py",
  "go",
  "java",
  "kt",
  "kts",
  "c",
  "h",
  "cpp",
  "hpp",
  "cc",
  "cs",
  "rb",
  "php",
  "sh",
  "bash",
  "zsh",
  "ps1",
  "sql",
  "xml",
  "svg",
  "csv",
  "tsv",
  "ini",
  "cfg",
  "conf",
  "env",
  "lock",
  "gradle",
  "dockerfile",
  "vue",
  "svelte",
  "astro",
  "graphql",
  "proto",
  "lua",
  "r",
  "swift",
  "dart",
  "ex",
  "exs",
  "log",
]);

function isTextFile(name: string, mime: string): boolean {
  if (mime.startsWith("text/")) return true;
  if (mime === "application/json" || mime === "application/xml") return true;
  const dot = name.lastIndexOf(".");
  const ext = dot >= 0 ? name.slice(dot + 1).toLowerCase() : name.toLowerCase();
  return TEXT_EXT.has(ext);
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} o`;
  const ko = bytes / 1024;
  if (ko < 1024) return `${ko.toFixed(1).replace(".", ",")} ko`;
  return `${(ko / 1024).toFixed(1).replace(".", ",")} Mo`;
}

const MAX_INLINE_CHARS = 24_000;

function githubRawCandidates(input: string): string[] {
  let url: URL;
  try {
    url = new URL(input.trim());
  } catch {
    return [];
  }
  if (url.hostname !== "github.com") return [];
  const parts = url.pathname.split("/").filter(Boolean);
  if (parts.length >= 5 && parts[2] === "blob") {
    const [owner, repo, , ref, ...rest] = parts;
    return [`https://raw.githubusercontent.com/${owner}/${repo}/${ref}/${rest.join("/")}`];
  }
  if (parts.length >= 2) {
    const [owner, repo] = parts;
    const branches = ["main", "master"];
    const names = ["README.md", "readme.md", "README.MD"];
    const out: string[] = [];
    for (const b of branches) {
      for (const n of names) {
        out.push(`https://raw.githubusercontent.com/${owner}/${repo}/${b}/${n}`);
      }
    }
    return out;
  }
  return [];
}

function htmlToText(html: string): string {
  const noScript = html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<!--[\s\S]*?-->/g, " ");
  const text = noScript.replace(/<[^>]+>/g, " ");
  const decoded = text
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
  return decoded
    .replace(/[ \t]+/g, " ")
    .replace(/\n\s*\n\s*\n+/g, "\n\n")
    .trim();
}

// ── Conversation + suggestions ───────────────────────────────────────────────

interface Turn {
  role: "user" | "assistant";
  text: string;
  pending?: boolean;
}

interface Suggestion {
  icon: string;
  label: string;
  prompt: string;
}

// Gemini 3.5 Flash is the chat model, served by the keyless Gemini web transport
// (the default backend). The id is passed to `aphrody chat --model`.
const MODELS = [{ id: "gemini-3.5-flash", label: "Gemini 3.5 Flash" }] as const;

const ACCEPT: Record<"image" | "video" | "audio", string> = {
  image: "image/*",
  video: "video/*",
  audio: "audio/*",
};

const SUGGESTIONS: Suggestion[] = [
  {
    icon: "edit",
    label: "Rédiger un message",
    prompt: "Aide-moi à rédiger un e-mail professionnel et clair.",
  },
  {
    icon: "school",
    label: "Expliquer un sujet",
    prompt: "Explique-moi un concept compliqué avec des mots simples.",
  },
  {
    icon: "lightbulb",
    label: "Trouver des idées",
    prompt: "Propose-moi des idées originales pour un projet.",
  },
  {
    icon: "summarize",
    label: "Résumer un texte",
    prompt: "Résume ce texte en quelques points clés : ",
  },
];

let idCounter = 0;
function nextId(): string {
  idCounter += 1;
  return `att-${idCounter}`;
}

export function Assistant() {
  const [turns, setTurns] = useState<Turn[]>([]);
  const [draft, setDraft] = useState("");
  const [busy, setBusy] = useState(false);
  const [model] = useState<(typeof MODELS)[number]>(MODELS[0]);
  const [attachments, setAttachments] = useState<Attachment[]>([]);
  const [linkPanel, setLinkPanel] = useState<"github" | "url" | "drive" | null>(null);
  const [linkValue, setLinkValue] = useState("");
  const [voiceMode, setVoiceMode] = useState(false);
  const speechSupported = voiceSupported();

  const scrollPane = useRef<HTMLDivElement>(null);
  const promptInput = useRef<HTMLTextAreaElement>(null);
  const fileInput = useRef<HTMLInputElement>(null);
  const pickerKind = useRef<AttachmentKind>("file");
  const busyRef = useRef(false);

  const hasConversation = turns.length > 0;

  useEffect(() => {
    const el = scrollPane.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [turns]);

  const autoGrow = useCallback(() => {
    const el = promptInput.current;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = `${Math.min(el.scrollHeight, 200)}px`;
  }, []);

  const onInput = (value: string) => {
    setDraft(value);
    autoGrow();
  };

  // ── Attachment patching ────────────────────────────────────────────────────

  const patchAttachment = useCallback((id: string, patch: Partial<Attachment>) => {
    setAttachments((list) => list.map((a) => (a.id === id ? { ...a, ...patch } : a)));
  }, []);

  const removeAttachment = (id: string) => {
    setAttachments((a) => a.filter((x) => x.id !== id));
  };

  const fetchInto = useCallback(
    async (id: string, urls: string[], stripHtml = false): Promise<void> => {
      for (const u of urls) {
        try {
          const res = await fetch(u, { redirect: "follow" });
          if (!res.ok) continue;
          let body = await res.text();
          const ct = res.headers.get("content-type") ?? "";
          if (stripHtml || ct.includes("text/html")) {
            body = htmlToText(body);
          }
          body = body.trim();
          if (!body) continue;
          const truncated = body.length > MAX_INLINE_CHARS;
          patchAttachment(id, {
            loading: false,
            text: truncated ? body.slice(0, MAX_INLINE_CHARS) : body,
            note: truncated ? "contenu tronqué (trop long)" : undefined,
          });
          return;
        } catch {
          // try the next candidate
        }
      }
      patchAttachment(id, {
        loading: false,
        note: "contenu non récupérable (réseau bloqué ou ressource privée) — lien tout de même référencé",
      });
    },
    [patchAttachment],
  );

  // ── Native file picker ──────────────────────────────────────────────────────

  const pickMedia = (kind: "image" | "video" | "audio" | "file") => {
    pickerKind.current = kind;
    const input = fileInput.current;
    if (!input) return;
    input.accept = kind === "file" ? "" : ACCEPT[kind];
    input.value = "";
    input.click();
  };

  const onFilesChosen = async (ev: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(ev.target.files ?? []);
    const kind = pickerKind.current;
    for (const file of files) {
      const textual = kind === "file" && isTextFile(file.name, file.type);
      const att: Attachment = {
        id: nextId(),
        kind,
        name: file.name,
        detail: `${formatBytes(file.size)}${file.type ? ` · ${file.type}` : ""}`,
        loading: textual,
      };
      setAttachments((a) => [...a, att]);
      if (textual) {
        try {
          const raw = await file.text();
          const text = raw.length > MAX_INLINE_CHARS ? raw.slice(0, MAX_INLINE_CHARS) : raw;
          patchAttachment(att.id, {
            loading: false,
            text,
            note: raw.length > MAX_INLINE_CHARS ? "contenu tronqué (trop long)" : undefined,
          });
        } catch (err) {
          patchAttachment(att.id, { loading: false, note: `lecture impossible : ${String(err)}` });
        }
      } else {
        patchAttachment(att.id, {
          note: "média binaire référencé (chat texte uniquement — pas d'analyse multimodale)",
        });
      }
    }
  };

  const addGithub = useCallback(
    async (url: string) => {
      const trimmed = url.trim();
      if (!trimmed) return;
      const candidates = githubRawCandidates(trimmed);
      const att: Attachment = {
        id: nextId(),
        kind: "github",
        name: trimmed,
        detail: "GitHub",
        loading: candidates.length > 0,
      };
      setAttachments((a) => [...a, att]);
      if (candidates.length === 0) {
        patchAttachment(att.id, {
          loading: false,
          note: "URL GitHub non reconnue (attendu : lien blob ou dépôt)",
        });
        return;
      }
      await fetchInto(att.id, candidates);
    },
    [fetchInto, patchAttachment],
  );

  const addUrl = useCallback(
    async (url: string) => {
      const trimmed = url.trim();
      if (!trimmed) return;
      let normalized = trimmed;
      if (!/^https?:\/\//i.test(normalized)) normalized = `https://${normalized}`;
      let host = normalized;
      try {
        host = new URL(normalized).hostname;
      } catch {
        // keep the raw string as detail
      }
      const att: Attachment = {
        id: nextId(),
        kind: "url",
        name: trimmed,
        detail: host,
        loading: true,
      };
      setAttachments((a) => [...a, att]);
      await fetchInto(att.id, [normalized], true);
    },
    [fetchInto],
  );

  const addDrive = (link: string) => {
    const trimmed = link.trim();
    if (!trimmed) return;
    setAttachments((a) => [
      ...a,
      {
        id: nextId(),
        kind: "drive",
        name: trimmed,
        detail: "Google Drive (lien)",
        note: "lien référencé tel quel (aucune authentification Drive)",
      },
    ]);
  };

  // ── Link panel ──────────────────────────────────────────────────────────────

  const openLinkPanel = (kind: "github" | "url" | "drive") => {
    setLinkValue("");
    setLinkPanel(kind);
  };
  const closeLinkPanel = () => setLinkPanel(null);

  const linkPlaceholder = (): string => {
    switch (linkPanel) {
      case "github":
        return "https://github.com/owner/repo ou .../blob/main/fichier.rs";
      case "drive":
        return "https://drive.google.com/file/d/…";
      default:
        return "https://exemple.com/article";
    }
  };

  const submitLink = () => {
    const kind = linkPanel;
    const v = linkValue.trim();
    if (kind && v) {
      if (kind === "github") void addGithub(v);
      else if (kind === "url") void addUrl(v);
      else addDrive(v);
    }
    closeLinkPanel();
  };

  // ── Prompt context + send ───────────────────────────────────────────────────

  const buildContext = useCallback((items: Attachment[]): string => {
    if (items.length === 0) return "";
    const blocks: string[] = [];
    for (const a of items) {
      const header = `[${kindLabel(a.kind)}] ${a.name}`;
      if (a.text) {
        blocks.push(`${header}\n\`\`\`\n${a.text}\n\`\`\``);
      } else {
        const reason = a.note ?? "référencé sans contenu textuel";
        blocks.push(`${header} (${reason})`);
      }
    }
    return `Contexte fourni par l'utilisateur :\n\n${blocks.join("\n\n")}`;
  }, []);

  const revealReply = useCallback(async (full: string, idx: number) => {
    const step = Math.max(1, Math.round(full.length / 240));
    for (let i = 0; i <= full.length; i += step) {
      const slice = full.slice(0, i);
      const pending = i < full.length;
      setTurns((t) => {
        const copy = [...t];
        copy[idx] = { role: "assistant", text: slice, pending };
        return copy;
      });
      await new Promise((r) => setTimeout(r, 12));
    }
    setTurns((t) => {
      const copy = [...t];
      copy[idx] = { role: "assistant", text: full, pending: false };
      return copy;
    });
  }, []);

  const send = useCallback(async () => {
    const prompt = draft.trim();
    const current = attachments;
    const hasAtt = current.length > 0;
    if ((!prompt && !hasAtt) || busyRef.current) return;
    busyRef.current = true;
    setBusy(true);

    const context = buildContext(current);
    const userVisible = prompt || "(voir le contexte joint)";
    const fullPrompt = context ? `${context}\n\n---\n\n${prompt}` : prompt;

    setDraft("");
    setAttachments([]);
    if (promptInput.current) promptInput.current.style.height = "auto";

    let assistantIdx = -1;
    setTurns((t) => {
      assistantIdx = t.length + 1;
      return [
        ...t,
        { role: "user", text: userVisible },
        { role: "assistant", text: "", pending: true },
      ];
    });

    let reply: string;
    try {
      // `--web` is the default chat transport (the only one serving real Gemini
      // 3.5 Flash); the CLI falls back to the agy token when the cookie jar is absent.
      const res = await run(["chat", "--prompt", fullPrompt, "--model", model.id, "--web"]);
      reply = (res.stdout || res.stderr || "").trim() || "(réponse vide)";
      if (res.code !== 0 && !res.stdout) {
        reply = `La commande a échoué (code ${res.code}).\n\n${res.stderr}`.trim();
      }
    } catch (err) {
      reply = `Erreur lors de l'appel au backend aphrody : ${String(err)}`;
    }

    await revealReply(reply, assistantIdx);
    busyRef.current = false;
    setBusy(false);
  }, [draft, attachments, model.id, buildContext, revealReply]);

  const onKeydown = (ev: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (ev.key === "Enter" && !ev.shiftKey) {
      ev.preventDefault();
      void send();
    }
  };

  const useSuggestion = (s: Suggestion) => {
    setDraft(s.prompt);
  };

  const newChat = () => {
    setTurns([]);
    setDraft("");
    setAttachments([]);
    busyRef.current = false;
    setBusy(false);
  };

  const canSend = draft.trim().length > 0 || attachments.length > 0;

  return (
    <div className="aph-assistant">
      {hasConversation ? (
        <div className="aph-assistant__conversation" ref={scrollPane}>
          <div className="aph-assistant__conversation-inner">
            {turns.map((turn, i) =>
              turn.role === "user" ? (
                <div key={i} className="aph-turn aph-turn--user">
                  <div className="aph-bubble aph-bubble--user">{turn.text}</div>
                </div>
              ) : (
                <div key={i} className="aph-turn aph-turn--assistant">
                  <div className="aph-assistant__avatar">
                    <MdIcon>auto_awesome</MdIcon>
                  </div>
                  <div className="aph-assistant__body">
                    {turn.pending && !turn.text ? (
                      <div className="aph-shimmer" aria-label="aphrody réfléchit">
                        <span></span>
                        <span></span>
                        <span></span>
                      </div>
                    ) : (
                      <div className={`aph-assistant__text${turn.pending ? " is-streaming" : ""}`}>
                        {turn.text}
                      </div>
                    )}
                  </div>
                </div>
              ),
            )}
          </div>
        </div>
      ) : (
        <div className="aph-assistant__hero">
          <h1 className="aph-assistant__hero-title">Par où commencer ?</h1>
        </div>
      )}

      <div className={`aph-composer-wrap${hasConversation ? " is-docked" : ""}`}>
        {hasConversation && (
          <MdIconButton
            className="aph-assistant__newchat"
            aria-label="Nouvelle conversation"
            title="Nouvelle conversation"
            onClick={newChat}
          >
            <MdIcon>add_comment</MdIcon>
          </MdIconButton>
        )}

        {attachments.length > 0 && (
          <div className="aph-chips" aria-label="Pièces jointes">
            {attachments.map((a) => (
              <div key={a.id} className={`aph-att-chip${a.loading ? " is-loading" : ""}`}>
                <MdIcon className="aph-att-chip__ico">{kindIcon(a.kind)}</MdIcon>
                <span className="aph-att-chip__meta">
                  <span className="aph-att-chip__name" title={a.name}>
                    {a.name}
                  </span>
                  {a.note ? (
                    <span className="aph-att-chip__note">{a.note}</span>
                  ) : (
                    a.detail && <span className="aph-att-chip__detail">{a.detail}</span>
                  )}
                </span>
                {a.loading ? (
                  <MdIcon className="aph-spin">progress_activity</MdIcon>
                ) : (
                  <MdIconButton
                    className="aph-att-chip__remove"
                    aria-label="Retirer"
                    onClick={() => removeAttachment(a.id)}
                  >
                    <MdIcon>close</MdIcon>
                  </MdIconButton>
                )}
              </div>
            ))}
          </div>
        )}

        {linkPanel && (
          <div className="aph-link-panel">
            <MdIcon>{kindIcon(linkPanel)}</MdIcon>
            <input
              className="aph-link-panel__input"
              autoFocus
              placeholder={linkPlaceholder()}
              value={linkValue}
              onChange={(e) => setLinkValue(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") submitLink();
                else if (e.key === "Escape") closeLinkPanel();
              }}
              aria-label="Adresse"
            />
            <MdIconButton aria-label="Ajouter" onClick={submitLink}>
              <MdIcon>add</MdIcon>
            </MdIconButton>
            <MdIconButton aria-label="Annuler" onClick={closeLinkPanel}>
              <MdIcon>close</MdIcon>
            </MdIconButton>
          </div>
        )}

        <div className="aph-composer">
          <Menu
            trigger={({ toggle }) => (
              <MdIconButton
                className="aph-composer__leading"
                title="Ajouter"
                aria-label="Ajouter une pièce jointe"
                onClick={toggle}
              >
                <MdIcon>add</MdIcon>
              </MdIconButton>
            )}
          >
            <MdMenuItem onClick={() => pickMedia("image")}>
              <MdIcon slot="start">image</MdIcon>
              <div slot="headline">Image</div>
            </MdMenuItem>
            <MdMenuItem onClick={() => pickMedia("video")}>
              <MdIcon slot="start">movie</MdIcon>
              <div slot="headline">Vidéo</div>
            </MdMenuItem>
            <MdMenuItem onClick={() => pickMedia("audio")}>
              <MdIcon slot="start">graphic_eq</MdIcon>
              <div slot="headline">Audio</div>
            </MdMenuItem>
            <MdMenuItem onClick={() => pickMedia("file")}>
              <MdIcon slot="start">description</MdIcon>
              <div slot="headline">Fichier (texte / code)</div>
            </MdMenuItem>
            <MdMenuItem onClick={() => openLinkPanel("github")}>
              <MdIcon slot="start">code</MdIcon>
              <div slot="headline">Lien GitHub</div>
            </MdMenuItem>
            <MdMenuItem onClick={() => openLinkPanel("url")}>
              <MdIcon slot="start">link</MdIcon>
              <div slot="headline">URL / Lien</div>
            </MdMenuItem>
            <MdMenuItem onClick={() => openLinkPanel("drive")}>
              <MdIcon slot="start">cloud</MdIcon>
              <div slot="headline">Google Drive</div>
            </MdMenuItem>
          </Menu>

          <input
            ref={fileInput}
            type="file"
            multiple
            className="aph-hidden-file"
            onChange={(e) => void onFilesChosen(e)}
            aria-hidden="true"
            tabIndex={-1}
          />

          <textarea
            ref={promptInput}
            className="aph-composer__input"
            rows={1}
            placeholder="Demandez à aphrody"
            value={draft}
            onChange={(e) => onInput(e.target.value)}
            onKeyDown={onKeydown}
            aria-label="Message"
          />

          <div className="aph-composer__trailing">
            <span className="aph-model-pill" title="Modèle de conversation">
              <span>{model.label}</span>
            </span>

            {speechSupported && !canSend && (
              <MdIconButton
                className="aph-mic-btn"
                onClick={() => setVoiceMode(true)}
                title="Mode vocal (conversation à voix haute)"
                aria-label="Mode vocal"
              >
                <MdIcon>graphic_eq</MdIcon>
              </MdIconButton>
            )}

            {canSend && (
              <MdIconButton
                className="aph-send-btn"
                onClick={() => void send()}
                disabled={busy}
                title="Envoyer"
                aria-label="Envoyer"
              >
                <MdIcon>arrow_upward</MdIcon>
              </MdIconButton>
            )}
          </div>
        </div>

        {!hasConversation && (
          <MdChipSet className="aph-suggestions" aria-label="Suggestions">
            {SUGGESTIONS.map((s) => (
              <MdAssistChip key={s.label} label={s.label} onClick={() => useSuggestion(s)}>
                <MdIcon slot="icon">{s.icon}</MdIcon>
              </MdAssistChip>
            ))}
          </MdChipSet>
        )}

        <p className="aph-disclaimer">
          aphrody peut afficher des informations inexactes. Vérifiez ses réponses.
        </p>
      </div>

      <VoiceOverlay open={voiceMode} onClose={() => setVoiceMode(false)} />
    </div>
  );
}

// apps/desktop/src/app/features/assistant/assistant.component.ts
// SPDX-License-Identifier: Apache-2.0
import {
  AfterViewChecked,
  Component,
  ElementRef,
  ViewChild,
  inject,
  signal,
} from "@angular/core";
import { FormsModule } from "@angular/forms";
import { MatButtonModule } from "@angular/material/button";
import { MatIconModule } from "@angular/material/icon";
import { MatMenuModule } from "@angular/material/menu";
import { MatTooltipModule } from "@angular/material/tooltip";

import { AphrodyService } from "../../core/aphrody.service";
import { SettingsService } from "../../core/settings.service";
import { SpeechService } from "../../core/speech.service";
import {
  Attachment,
  AttachmentKind,
  MAX_INLINE_CHARS,
  formatBytes,
  githubRawCandidates,
  isTextFile,
  kindIcon,
  kindLabel,
} from "./attachment";
import { VoiceOverlayComponent } from "./voice-overlay.component";

interface Turn {
  role: "user" | "assistant";
  text: string;
  /** assistant turn is still streaming/awaiting the reply */
  pending?: boolean;
}

interface Suggestion {
  icon: string;
  label: string;
  prompt: string;
}

// Gemini 3.5 Flash is the chat model. It is served by the keyless Gemini web
// transport (the default backend, see SettingsService) -- the agy/Cloud Code
// token path does NOT serve gemini-3.5-flash (404), so the GUI defaults to
// `--web`. The id below is passed to `aphrody chat --model`; the web backend
// maps it to its "3.5 Flash" model, and on the agy fallback it is ignored in
// favour of a served model.
const MODELS = [{ id: "gemini-3.5-flash", label: "Gemini 3.5 Flash" }] as const;

/** Accept filters for the native file picker, per media menu entry. */
const ACCEPT: Record<"image" | "video" | "audio", string> = {
  image: "image/*",
  video: "video/*",
  audio: "audio/*",
};

/**
 * The Assistant view = the Gemini empty-state hero + composer + conversation.
 * On submit the prompt (plus any attached context) becomes a user turn and
 * `aphrody chat --prompt` streams the reply, revealed character by character.
 * The composer mic opens a full voice-to-voice overlay; a "+" menu attaches
 * media / links / files whose textual content is honestly inlined as context.
 */
@Component({
  selector: "app-assistant",
  imports: [
    FormsModule,
    MatButtonModule,
    MatIconModule,
    MatMenuModule,
    MatTooltipModule,
    VoiceOverlayComponent,
  ],
  templateUrl: "./assistant.component.html",
  styleUrl: "./assistant.component.scss",
})
export class AssistantComponent implements AfterViewChecked {
  private readonly aphrody = inject(AphrodyService);
  private readonly settings = inject(SettingsService);
  readonly speech = inject(SpeechService);

  @ViewChild("scrollPane") private scrollPane?: ElementRef<HTMLElement>;
  @ViewChild("promptInput") private promptInput?: ElementRef<HTMLTextAreaElement>;
  @ViewChild("fileInput") private fileInput?: ElementRef<HTMLInputElement>;

  readonly turns = signal<Turn[]>([]);
  readonly draft = signal("");
  readonly busy = signal(false);
  readonly models = MODELS;
  readonly model = signal<(typeof MODELS)[number]>(MODELS[0]);

  /** Composer attachments (chips above the textarea). */
  readonly attachments = signal<Attachment[]>([]);
  /** True while the voice-to-voice overlay is mounted. */
  readonly voiceMode = signal(false);
  /** Which inline link-entry panel is open (null = none). */
  readonly linkPanel = signal<"github" | "url" | "drive" | null>(null);

  /** Pending native-picker accept filter + kind for the hidden <input>. */
  private pickerKind: AttachmentKind = "file";

  private shouldScroll = false;
  private idCounter = 0;

  // Re-export helpers for the template.
  readonly kindIcon = kindIcon;
  readonly kindLabel = kindLabel;

  readonly suggestions: Suggestion[] = [
    {
      icon: "edit",
      label: "Rédiger un message",
      prompt: "Aide-moi à rédiger un e-mail professionnel et clair.",
    },
    {
      icon: "school",
      label: "Expliquer un sujet",
      prompt: "Explique-moi un concept compliqué avec des mots simples.",
    },
    {
      icon: "lightbulb",
      label: "Trouver des idées",
      prompt: "Propose-moi des idées originales pour un projet.",
    },
    {
      icon: "summarize",
      label: "Résumer un texte",
      prompt: "Résume ce texte en quelques points clés : ",
    },
  ];

  get hasConversation(): boolean {
    return this.turns().length > 0;
  }

  ngAfterViewChecked(): void {
    if (this.shouldScroll && this.scrollPane) {
      this.scrollPane.nativeElement.scrollTop = this.scrollPane.nativeElement.scrollHeight;
      this.shouldScroll = false;
    }
  }

  onInput(value: string): void {
    this.draft.set(value);
    this.autoGrow();
  }

  private autoGrow(): void {
    const el = this.promptInput?.nativeElement;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = `${Math.min(el.scrollHeight, 200)}px`;
  }

  onKeydown(ev: KeyboardEvent): void {
    if (ev.key === "Enter" && !ev.shiftKey) {
      ev.preventDefault();
      void this.send();
    }
  }

  useSuggestion(s: Suggestion): void {
    this.draft.set(s.prompt);
    void this.send();
  }

  // ── Voice mode ─────────────────────────────────────────────────────────

  /** Open the full voice-to-voice overlay. */
  openVoice(): void {
    if (!this.speech.supported()) {
      return;
    }
    this.speech.stop();
    this.voiceMode.set(true);
  }

  closeVoice(): void {
    this.voiceMode.set(false);
  }

  /** Short dictation into the textarea (keeps the classic mic affordance). */
  dictate(): void {
    this.speech.toggle((text, isFinal) => {
      const base = this.draft();
      if (isFinal) {
        this.draft.set(`${base}${text} `);
      } else {
        this.draft.set(`${base}${text}`);
      }
      this.autoGrow();
    });
  }

  // ── Attachments ──────────────────────────────────────────────────────────

  private nextId(): string {
    this.idCounter += 1;
    return `att-${this.idCounter}`;
  }

  /** Trigger the native file picker for a media kind. */
  pickMedia(kind: "image" | "video" | "audio" | "file"): void {
    this.pickerKind = kind;
    const input = this.fileInput?.nativeElement;
    if (!input) return;
    input.accept = kind === "file" ? "" : ACCEPT[kind];
    input.value = "";
    input.click();
  }

  /** Handle the chosen file(s): inline text/code, reference binary media. */
  async onFilesChosen(ev: Event): Promise<void> {
    const input = ev.target as HTMLInputElement;
    const files = Array.from(input.files ?? []);
    for (const file of files) {
      const textual = this.pickerKind === "file" && isTextFile(file.name, file.type);
      const att: Attachment = {
        id: this.nextId(),
        kind: this.pickerKind,
        name: file.name,
        detail: `${formatBytes(file.size)}${file.type ? ` · ${file.type}` : ""}`,
        loading: textual,
      };
      this.attachments.update((a) => [...a, att]);
      if (textual) {
        try {
          const raw = await file.text();
          const text = raw.length > MAX_INLINE_CHARS ? raw.slice(0, MAX_INLINE_CHARS) : raw;
          const truncated = raw.length > MAX_INLINE_CHARS;
          this.patchAttachment(att.id, {
            loading: false,
            text,
            note: truncated ? "contenu tronqué (trop long)" : undefined,
          });
        } catch (err) {
          this.patchAttachment(att.id, { loading: false, note: `lecture impossible : ${String(err)}` });
        }
      } else {
        // Binary media: referenced honestly, NOT decoded as vision input.
        this.patchAttachment(att.id, {
          note: "média binaire référencé (chat texte uniquement — pas d'analyse multimodale)",
        });
      }
    }
  }

  /** Add a GitHub link: fetch the raw file / README and inline its text. */
  async addGithub(url: string): Promise<void> {
    const trimmed = url.trim();
    if (!trimmed) return;
    const candidates = githubRawCandidates(trimmed);
    const att: Attachment = {
      id: this.nextId(),
      kind: "github",
      name: trimmed,
      detail: "GitHub",
      loading: candidates.length > 0,
    };
    this.attachments.update((a) => [...a, att]);
    if (candidates.length === 0) {
      this.patchAttachment(att.id, {
        loading: false,
        note: "URL GitHub non reconnue (attendu : lien blob ou dépôt)",
      });
      return;
    }
    await this.fetchInto(att.id, candidates);
  }

  /** Add an arbitrary URL: fetch the page and inline its visible text. */
  async addUrl(url: string): Promise<void> {
    const trimmed = url.trim();
    if (!trimmed) return;
    let normalized = trimmed;
    if (!/^https?:\/\//i.test(normalized)) {
      normalized = `https://${normalized}`;
    }
    let host = normalized;
    try {
      host = new URL(normalized).hostname;
    } catch {
      // keep the raw string as detail
    }
    const att: Attachment = {
      id: this.nextId(),
      kind: "url",
      name: trimmed,
      detail: host,
      loading: true,
    };
    this.attachments.update((a) => [...a, att]);
    await this.fetchInto(att.id, [normalized], true);
  }

  // ── Inline link-entry panel ──────────────────────────────────────────────

  openLinkPanel(kind: "github" | "url" | "drive"): void {
    this.linkPanel.set(kind);
  }

  closeLinkPanel(): void {
    this.linkPanel.set(null);
  }

  linkPlaceholder(): string {
    switch (this.linkPanel()) {
      case "github":
        return "https://github.com/owner/repo ou .../blob/main/fichier.rs";
      case "drive":
        return "https://drive.google.com/file/d/…";
      default:
        return "https://exemple.com/article";
    }
  }

  /** Commit the inline link panel input to the right attachment handler. */
  submitLink(value: string): void {
    const kind = this.linkPanel();
    const v = value.trim();
    if (kind && v) {
      if (kind === "github") {
        void this.addGithub(v);
      } else if (kind === "url") {
        void this.addUrl(v);
      } else {
        this.addDrive(v);
      }
    }
    this.closeLinkPanel();
  }

  /** Add a Google Drive link (paste-only; no OAuth, no fetch). */
  addDrive(link: string): void {
    const trimmed = link.trim();
    if (!trimmed) return;
    this.attachments.update((a) => [
      ...a,
      {
        id: this.nextId(),
        kind: "drive",
        name: trimmed,
        detail: "Google Drive (lien)",
        note: "lien référencé tel quel (aucune authentification Drive)",
      },
    ]);
  }

  /**
   * Fetch the first reachable candidate URL and inline its text. `stripHtml`
   * converts an HTML page to rough visible text. Failure is non-fatal: the chip
   * keeps a clear note and the link is still referenced in the prompt.
   */
  private async fetchInto(id: string, urls: string[], stripHtml = false): Promise<void> {
    for (const u of urls) {
      try {
        const res = await fetch(u, { redirect: "follow" });
        if (!res.ok) continue;
        let body = await res.text();
        const ct = res.headers.get("content-type") ?? "";
        if (stripHtml || ct.includes("text/html")) {
          body = this.htmlToText(body);
        }
        body = body.trim();
        if (!body) continue;
        const truncated = body.length > MAX_INLINE_CHARS;
        this.patchAttachment(id, {
          loading: false,
          text: truncated ? body.slice(0, MAX_INLINE_CHARS) : body,
          detail: `${this.attachmentById(id)?.detail ?? ""} · ${formatBytes(body.length)}`,
          note: truncated ? "contenu tronqué (trop long)" : undefined,
        });
        return;
      } catch {
        // try the next candidate
      }
    }
    this.patchAttachment(id, {
      loading: false,
      note: "contenu non récupérable (réseau bloqué ou ressource privée) — lien tout de même référencé",
    });
  }

  /** Strip tags/scripts from HTML, returning collapsed visible text. */
  private htmlToText(html: string): string {
    const noScript = html
      .replace(/<script[\s\S]*?<\/script>/gi, " ")
      .replace(/<style[\s\S]*?<\/style>/gi, " ")
      .replace(/<!--[\s\S]*?-->/g, " ");
    const text = noScript.replace(/<[^>]+>/g, " ");
    const decoded = text
      .replace(/&nbsp;/g, " ")
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'");
    return decoded.replace(/[ \t]+/g, " ").replace(/\n\s*\n\s*\n+/g, "\n\n").trim();
  }

  private attachmentById(id: string): Attachment | undefined {
    return this.attachments().find((a) => a.id === id);
  }

  private patchAttachment(id: string, patch: Partial<Attachment>): void {
    this.attachments.update((list) => list.map((a) => (a.id === id ? { ...a, ...patch } : a)));
  }

  removeAttachment(id: string): void {
    this.attachments.update((a) => a.filter((x) => x.id !== id));
  }

  /** Build the context block honestly folded into the prompt. */
  private buildContext(): string {
    const items = this.attachments();
    if (items.length === 0) return "";
    const blocks: string[] = [];
    for (const a of items) {
      const header = `[${kindLabel(a.kind)}] ${a.name}`;
      if (a.text) {
        blocks.push(`${header}\n\`\`\`\n${a.text}\n\`\`\``);
      } else {
        const reason = a.note ?? "référencé sans contenu textuel";
        blocks.push(`${header} (${reason})`);
      }
    }
    return `Contexte fourni par l'utilisateur :\n\n${blocks.join("\n\n")}`;
  }

  // ── Send ───────────────────────────────────────────────────────────────

  async send(): Promise<void> {
    const prompt = this.draft().trim();
    const hasAtt = this.attachments().length > 0;
    if ((!prompt && !hasAtt) || this.busy()) {
      return;
    }
    this.speech.stop();
    this.busy.set(true);

    const context = this.buildContext();
    const userVisible = prompt || "(voir le contexte joint)";
    const fullPrompt = context ? `${context}\n\n---\n\n${prompt}` : prompt;

    this.draft.set("");
    this.attachments.set([]);
    if (this.promptInput) {
      this.promptInput.nativeElement.style.height = "auto";
    }

    // Push the user turn (visible text only) + a pending assistant turn.
    this.turns.update((t) => [
      ...t,
      { role: "user", text: userVisible },
      { role: "assistant", text: "", pending: true },
    ]);
    this.shouldScroll = true;

    let reply: string;
    try {
      const res = await this.aphrody.exec([
        "chat",
        "--prompt",
        fullPrompt,
        "--model",
        this.model().id,
        ...this.settings.extraChatArgs(),
      ]);
      reply = (res.stdout || res.stderr || "").trim() || "(réponse vide)";
      if (res.code !== 0 && !res.stdout) {
        reply = `La commande a échoué (code ${res.code}).\n\n${res.stderr}`.trim();
      }
    } catch (err) {
      reply = `Erreur lors de l'appel au backend aphrody : ${String(err)}`;
    }

    await this.revealReply(reply);
    this.busy.set(false);
  }

  /** Reveal the assistant reply Gemini-style, a few chars per frame. */
  private async revealReply(full: string): Promise<void> {
    const idx = this.turns().length - 1;
    const step = Math.max(1, Math.round(full.length / 240));
    for (let i = 0; i <= full.length; i += step) {
      const slice = full.slice(0, i);
      this.turns.update((t) => {
        const copy = [...t];
        copy[idx] = { role: "assistant", text: slice, pending: i < full.length };
        return copy;
      });
      this.shouldScroll = true;
      await new Promise((r) => setTimeout(r, 12));
    }
    this.turns.update((t) => {
      const copy = [...t];
      copy[idx] = { role: "assistant", text: full, pending: false };
      return copy;
    });
    this.shouldScroll = true;
  }

  newChat(): void {
    this.speech.stop();
    this.turns.set([]);
    this.draft.set("");
    this.attachments.set([]);
    this.busy.set(false);
  }
}

<!-- SPDX-License-Identifier: Apache-2.0 -->
<div class="assistant">
    @if (hasConversation) {
        <div class="conversation" #scrollPane>
            <div class="conversation-inner">
                @for (turn of turns(); track $index) {
                    @if (turn.role === "user") {
                        <div class="turn turn-user">
                            <div class="bubble bubble-user">{{ turn.text }}</div>
                        </div>
                    } @else {
                        <div class="turn turn-assistant">
                            <div class="assistant-avatar">
                                <img src="assets/aphrody.webp" alt="aphrody" />
                            </div>
                            <div class="assistant-body">
                                @if (turn.pending && !turn.text) {
                                    <div class="shimmer" aria-label="aphrody réfléchit">
                                        <span></span><span></span><span></span>
                                    </div>
                                } @else {
                                    <div class="assistant-text" [class.streaming]="turn.pending">
                                        {{ turn.text }}
                                    </div>
                                }
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    } @else {
        <div class="hero">
            <h1 class="hero-title">Par où commencer ?</h1>
        </div>
    }

    <!-- Composer (the Gemini pill) -->
    <div class="composer-wrap" [class.docked]="hasConversation">
        <!-- Attachment chips -->
        @if (attachments().length > 0) {
            <div class="chips" aria-label="Pièces jointes">
                @for (a of attachments(); track a.id) {
                    <div class="att-chip" [class.loading]="a.loading">
                        <mat-icon class="material-symbols-outlined att-ico">{{
                            kindIcon(a.kind)
                        }}</mat-icon>
                        <span class="att-meta">
                            <span class="att-name" [title]="a.name">{{ a.name }}</span>
                            @if (a.note) {
                                <span class="att-note">{{ a.note }}</span>
                            } @else if (a.detail) {
                                <span class="att-detail">{{ a.detail }}</span>
                            }
                        </span>
                        @if (a.loading) {
                            <mat-icon class="material-symbols-outlined spin"
                                >progress_activity</mat-icon
                            >
                        } @else {
                            <button
                                class="att-remove"
                                (click)="removeAttachment(a.id)"
                                aria-label="Retirer"
                            >
                                <mat-icon class="material-symbols-outlined">close</mat-icon>
                            </button>
                        }
                    </div>
                }
            </div>
        }

        <!-- Inline link entry panel (URL / GitHub / Drive) -->
        @if (linkPanel()) {
            <div class="link-panel">
                <mat-icon class="material-symbols-outlined">{{ kindIcon(linkPanel()!) }}</mat-icon>
                <input
                    class="link-input"
                    #linkInput
                    [placeholder]="linkPlaceholder()"
                    (keydown.enter)="submitLink(linkInput.value)"
                    (keydown.escape)="closeLinkPanel()"
                    aria-label="Adresse"
                />
                <button class="link-add" (click)="submitLink(linkInput.value)" aria-label="Ajouter">
                    <mat-icon class="material-symbols-outlined">add</mat-icon>
                </button>
                <button class="link-cancel" (click)="closeLinkPanel()" aria-label="Annuler">
                    <mat-icon class="material-symbols-outlined">close</mat-icon>
                </button>
            </div>
        }

        <div class="composer">
            <button
                mat-icon-button
                class="composer-leading"
                [matMenuTriggerFor]="addMenu"
                matTooltip="Ajouter"
                aria-label="Ajouter une pièce jointe"
            >
                <mat-icon class="material-symbols-outlined">add</mat-icon>
            </button>
            <mat-menu #addMenu="matMenu">
                <button mat-menu-item (click)="pickMedia('image')">
                    <mat-icon class="material-symbols-outlined">image</mat-icon>
                    <span>Image</span>
                </button>
                <button mat-menu-item (click)="pickMedia('video')">
                    <mat-icon class="material-symbols-outlined">movie</mat-icon>
                    <span>Vidéo</span>
                </button>
                <button mat-menu-item (click)="pickMedia('audio')">
                    <mat-icon class="material-symbols-outlined">graphic_eq</mat-icon>
                    <span>Audio</span>
                </button>
                <button mat-menu-item (click)="pickMedia('file')">
                    <mat-icon class="material-symbols-outlined">description</mat-icon>
                    <span>Fichier (texte / code)</span>
                </button>
                <button mat-menu-item (click)="openLinkPanel('github')">
                    <mat-icon class="material-symbols-outlined">code</mat-icon>
                    <span>Lien GitHub</span>
                </button>
                <button mat-menu-item (click)="openLinkPanel('url')">
                    <mat-icon class="material-symbols-outlined">link</mat-icon>
                    <span>URL / Lien</span>
                </button>
                <button mat-menu-item (click)="openLinkPanel('drive')">
                    <mat-icon class="material-symbols-outlined">cloud</mat-icon>
                    <span>Google Drive</span>
                </button>
            </mat-menu>

            <input
                #fileInput
                type="file"
                multiple
                class="hidden-file"
                (change)="onFilesChosen($event)"
                aria-hidden="true"
                tabindex="-1"
            />

            <textarea
                #promptInput
                class="composer-input"
                rows="1"
                placeholder="Demandez à aphrody"
                [value]="draft()"
                (input)="onInput($any($event.target).value)"
                (keydown)="onKeydown($event)"
                aria-label="Message"
            ></textarea>

            <div class="composer-trailing">
                <button
                    mat-button
                    class="model-pill"
                    [matMenuTriggerFor]="modelMenu"
                    matTooltip="Choisir le modèle"
                >
                    <span>{{ model().label }}</span>
                    <mat-icon class="material-symbols-outlined chevron">expand_more</mat-icon>
                </button>
                <mat-menu #modelMenu="matMenu">
                    @for (m of models; track m.id) {
                        <button mat-menu-item (click)="model.set(m)">
                            <mat-icon class="material-symbols-outlined">{{
                                model().id === m.id ? "check" : ""
                            }}</mat-icon>
                            <span>{{ m.label }}</span>
                        </button>
                    }
                </mat-menu>

                @if (speech.supported()) {
                    @if (draft().trim().length > 0) {
                        <!-- While typing, the mic does quick dictation into the field. -->
                        <button
                            mat-icon-button
                            class="mic-btn"
                            [class.recording]="speech.listening()"
                            (click)="dictate()"
                            [matTooltip]="
                                speech.listening() ? 'Arrêter la dictée' : 'Dictée vocale (fr-FR)'
                            "
                            aria-label="Dictée vocale"
                        >
                            <mat-icon class="material-symbols-outlined">{{
                                speech.listening() ? "mic" : "mic_none"
                            }}</mat-icon>
                        </button>
                    } @else {
                        <!-- Empty field: the mic opens the full voice-to-voice mode. -->
                        <button
                            mat-icon-button
                            class="mic-btn voice"
                            (click)="openVoice()"
                            matTooltip="Mode vocal (conversation à voix haute)"
                            aria-label="Mode vocal"
                        >
                            <mat-icon class="material-symbols-outlined">graphic_eq</mat-icon>
                        </button>
                    }
                }

                @if (draft().trim().length > 0 || attachments().length > 0) {
                    <button
                        mat-icon-button
                        class="send-btn"
                        (click)="send()"
                        [disabled]="busy()"
                        matTooltip="Envoyer"
                        aria-label="Envoyer"
                    >
                        <mat-icon class="material-symbols-outlined fill">arrow_upward</mat-icon>
                    </button>
                }
            </div>
        </div>

        @if (!hasConversation) {
            <div class="suggestions">
                @for (s of suggestions; track s.label) {
                    <button class="chip" (click)="useSuggestion(s)">
                        <mat-icon class="material-symbols-outlined">{{ s.icon }}</mat-icon>
                        <span>{{ s.label }}</span>
                    </button>
                }
            </div>
        }

        <p class="disclaimer">
            aphrody peut afficher des informations inexactes. Vérifiez ses réponses.
        </p>
    </div>
</div>

@if (voiceMode()) {
    <app-voice-overlay (closed)="closeVoice()" />
}
