// apps/desktop/src/app/shared/tool-runner/tool-runner.component.ts
// SPDX-License-Identifier: Apache-2.0
import { Component, inject, input, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { MatButtonModule } from "@angular/material/button";
import { MatIconModule } from "@angular/material/icon";
import { MatProgressSpinnerModule } from "@angular/material/progress-spinner";

import { AphrodyService, ExecResult } from "../../core/aphrody.service";

/** A single runnable aphrody command exposed in a tool view. */
export interface ToolAction {
  /** Human label shown on the button. */
  label: string;
  /** Material Symbol name. */
  icon: string;
  /** argv passed to `aphrody_exec` (without program name). */
  args: string[];
  /** Optional free-text input appended to args when present. */
  prompt?: { placeholder: string; flag?: string };
  /** Longer help text. */
  hint?: string;
}

/**
 * Generic tool surface: a titled header, a column of runnable actions (each
 * calls `aphrody_exec`), and a terminal-style output pane with the captured
 * stdout/stderr + exit code.
 */
@Component({
  selector: "app-tool-runner",
  imports: [FormsModule, MatButtonModule, MatIconModule, MatProgressSpinnerModule],
  templateUrl: "./tool-runner.component.html",
  styleUrl: "./tool-runner.component.scss",
})
export class ToolRunnerComponent {
  private readonly aphrody = inject(AphrodyService);

  readonly title = input.required<string>();
  readonly subtitle = input<string>("");
  readonly icon = input<string>("build");
  readonly actions = input.required<ToolAction[]>();

  readonly running = signal<string | null>(null);
  readonly result = signal<ExecResult | null>(null);
  readonly ranLabel = signal<string>("");
  readonly inputs = signal<Record<string, string>>({});

  setInput(label: string, value: string): void {
    this.inputs.update((m) => ({ ...m, [label]: value }));
  }

  /** Current input value for an action label (empty string when unset). */
  inputValue(label: string): string {
    return this.inputs()[label] ?? "";
  }

  async run(action: ToolAction): Promise<void> {
    if (this.running()) {
      return;
    }
    const args = [...action.args];
    if (action.prompt) {
      const val = (this.inputs()[action.label] ?? "").trim();
      if (val) {
        if (action.prompt.flag) {
          args.push(action.prompt.flag, val);
        } else {
          args.push(val);
        }
      }
    }
    this.running.set(action.label);
    this.result.set(null);
    this.ranLabel.set(["aphrody", ...args].join(" "));
    try {
      const res = await this.aphrody.exec(args);
      this.result.set(res);
    } catch (err) {
      this.result.set({ code: -1, stdout: "", stderr: String(err) });
    } finally {
      this.running.set(null);
    }
  }
}

<!-- SPDX-License-Identifier: Apache-2.0 -->
<div class="tool">
    <header class="tool-head">
        <div class="tool-icon">
            <mat-icon class="material-symbols-outlined">{{ icon() }}</mat-icon>
        </div>
        <div>
            <h1>{{ title() }}</h1>
            @if (subtitle()) {
                <p>{{ subtitle() }}</p>
            }
        </div>
    </header>

    <div class="tool-body">
        <section class="actions">
            @for (a of actions(); track a.label) {
                <div class="action-card">
                    <div class="action-main">
                        <mat-icon class="material-symbols-outlined action-glyph">{{
                            a.icon
                        }}</mat-icon>
                        <div class="action-text">
                            <span class="action-label">{{ a.label }}</span>
                            @if (a.hint) {
                                <span class="action-hint">{{ a.hint }}</span>
                            }
                        </div>
                    </div>
                    <div class="action-controls">
                        @if (a.prompt) {
                            <input
                                class="action-input"
                                [placeholder]="a.prompt.placeholder"
                                [value]="inputValue(a.label)"
                                (input)="setInput(a.label, $any($event.target).value)"
                            />
                        }
                        <button
                            mat-flat-button
                            class="run-btn"
                            (click)="run(a)"
                            [disabled]="running() !== null"
                        >
                            @if (running() === a.label) {
                                <mat-spinner diameter="18"></mat-spinner>
                            } @else {
                                <mat-icon class="material-symbols-outlined">play_arrow</mat-icon>
                            }
                            Exécuter
                        </button>
                    </div>
                </div>
            }
        </section>

        <section class="output">
            <div class="output-head">
                <mat-icon class="material-symbols-outlined">terminal</mat-icon>
                <span class="cmd">{{ ranLabel() || "Aucune commande exécutée" }}</span>
                @if (result(); as r) {
                    <span class="code" [class.ok]="r.code === 0" [class.err]="r.code !== 0">
                        code {{ r.code }}
                    </span>
                }
            </div>
            <pre
                class="output-body"
            >@if (running()) {<span class="run-note">Exécution en cours...</span>} @else if (result(); as r) {{{ r.stdout }}@if (r.stderr) {
{{ r.stderr }}}} @else {<span class="placeholder">La sortie de la commande s'affichera ici.</span>}</pre>
        </section>
    </div>
</div>

// apps/web/src/aphrody/ToolRunner.tsx
// Generic tool surface (port of Angular ToolRunnerComponent): a header, a column
// of runnable aphrody commands (each calls `run`), and a terminal-style output
// pane with captured stdout/stderr + exit code. Many feature panels are just a
// title + a list of ToolActions fed to this component.

import { useState } from "react";
import {
  MdCircularProgress,
  MdFilledButton,
  MdIcon,
  MdOutlinedTextField,
} from "@aphrody-code/m3-react";
import { run } from "./client.ts";
import type { ExecResult } from "./types.ts";

/** A single runnable aphrody command exposed in a tool view. */
export interface ToolAction {
  label: string;
  icon: string;
  /** argv passed to the runner (without program name). */
  args: string[];
  /** Optional free-text input appended to args when present. */
  prompt?: { placeholder: string; flag?: string };
  hint?: string;
}

export function ToolRunner({
  title,
  subtitle,
  icon = "build",
  actions,
}: {
  title: string;
  subtitle?: string;
  icon?: string;
  actions: ToolAction[];
}) {
  const [running, setRunning] = useState<string | null>(null);
  const [result, setResult] = useState<ExecResult | null>(null);
  const [ranLabel, setRanLabel] = useState("");
  const [inputs, setInputs] = useState<Record<string, string>>({});

  const exec = async (action: ToolAction) => {
    if (running) return;
    const args = [...action.args];
    if (action.prompt) {
      const val = (inputs[action.label] ?? "").trim();
      if (val) {
        if (action.prompt.flag) args.push(action.prompt.flag, val);
        else args.push(val);
      }
    }
    setRunning(action.label);
    setResult(null);
    setRanLabel(["aphrody", ...args].join(" "));
    const res = await run(args);
    setResult(res);
    setRunning(null);
  };

  return (
    <div className="aph-tool">
      <header className="aph-tool__head">
        <span className="aph-tool__glyph">
          <MdIcon>{icon}</MdIcon>
        </span>
        <div>
          <h1 className="aph-pagehead__title">{title}</h1>
          {subtitle && <p className="aph-muted">{subtitle}</p>}
        </div>
      </header>

      <div className="aph-tool__body">
        <section className="aph-actions">
          {actions.map((a) => (
            <div key={a.label} className="aph-action">
              <div className="aph-row aph-action__main">
                <MdIcon className="aph-action__glyph">{a.icon}</MdIcon>
                <div className="aph-action__text">
                  <span className="aph-action__label">{a.label}</span>
                  {a.hint && <span className="aph-muted aph-action__hint">{a.hint}</span>}
                </div>
              </div>
              <div className="aph-action__controls">
                {a.prompt && (
                  <MdOutlinedTextField
                    className="aph-action__input"
                    placeholder={a.prompt.placeholder}
                    value={inputs[a.label] ?? ""}
                    onInput={(e) =>
                      setInputs((m) => ({ ...m, [a.label]: (e.target as HTMLInputElement).value }))
                    }
                  />
                )}
                <MdFilledButton disabled={running !== null} onClick={() => void exec(a)}>
                  {running === a.label ? (
                    <MdCircularProgress indeterminate slot="icon" />
                  ) : (
                    <MdIcon slot="icon">play_arrow</MdIcon>
                  )}
                  Exécuter
                </MdFilledButton>
              </div>
            </div>
          ))}
        </section>

        <section className="aph-output aph-output--tool">
          <div className="aph-output__head">
            <MdIcon>terminal</MdIcon>
            <span className="aph-output__cmd">{ranLabel || "Aucune commande exécutée"}</span>
            {result && (
              <span className={`aph-code ${result.code === 0 ? "aph-code--ok" : "aph-code--err"}`}>
                code {result.code}
              </span>
            )}
          </div>
          <pre className="aph-output__body">
            {running
              ? "Exécution en cours…"
              : result
                ? `${result.stdout}${result.stderr ? `\n${result.stderr}` : ""}`
                : "La sortie de la commande s'affichera ici."}
          </pre>
        </section>
      </div>
    </div>
  );
}
